// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnamlc47JPiVsKnzWWc60qgf1oLt0ER8',
    appId: '1:1061501894606:web:be0a2f7e2d363a5103359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    authDomain: 'brahmin-marriage-app.firebaseapp.com',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    measurementId: 'G-KZMBPC9MDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxyys93AiPI1l4YP11tS8WKWEICIT9hg',
    appId: '1:1061501894606:android:33bf0f56a84c2c4f03359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DEIT45NXaCtwdXp9IfJo6vJZbtuX5cg',
    appId: '1:1061501894606:ios:ee3dc5ed33ca7cfd03359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    iosBundleId: 'com.example.brahminMarriage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5DEIT45NXaCtwdXp9IfJo6vJZbtuX5cg',
    appId: '1:1061501894606:ios:ee3dc5ed33ca7cfd03359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    iosBundleId: 'com.example.brahminMarriage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwnamlc47JPiVsKnzWWc60qgf1oLt0ER8',
    appId: '1:1061501894606:web:04da05f023bdf25703359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    authDomain: 'brahmin-marriage-app.firebaseapp.com',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    measurementId: 'G-D03W2BS7JH',
  );
}
