// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:1061501894606:web:be0a2f7e2d363a5103359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    authDomain: 'brahmin-marriage-app.firebaseapp.com',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    measurementId: 'G-KZMBPC9MDK',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:1061501894606:android:33bf0f56a84c2c4f03359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:1061501894606:ios:ee3dc5ed33ca7cfd03359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    iosBundleId: 'com.example.brahminMarriage',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:1061501894606:ios:ee3dc5ed33ca7cfd03359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    iosBundleId: 'com.example.brahminMarriage',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY']!,
    appId: '1:1061501894606:web:04da05f023bdf25703359f',
    messagingSenderId: '1061501894606',
    projectId: 'brahmin-marriage-app',
    authDomain: 'brahmin-marriage-app.firebaseapp.com',
    storageBucket: 'brahmin-marriage-app.firebasestorage.app',
    measurementId: 'G-D03W2BS7JH',
  );
}
